# This file was generated by GoReleaser. DO NOT EDIT.
cask "durablex" do
  version "0.1.0-beta.2"

  on_macos do
    on_intel do
      sha256 "677e8f0a3b23eea8ea4e8e63f0909347d546ad294e64eef4437ba714657526a3"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f7d1e05a1e5c3ab7ebefd21ae3b20c84919088ab6cac2d1e3d58ba43fc088c5"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "08f213dba18afe45b0ac21a763ae111cc4b7fabbfba94aab37132f608ee36417"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a830d9d67da331c0cc1eab26fd325478445acb56eb82a9bf43e236f107a58827"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_linux_arm64.tar.gz"
    end
  end

  name "durablex"
  desc "Durable workflow engine - a single Go binary with an embedded dashboard"
  homepage "https://github.com/easydep/durablex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "durablex"

  # No zap stanza required

end
