# This file was generated by GoReleaser. DO NOT EDIT.
cask "durablex" do
  version "0.1.0-beta.2"

  on_macos do
    on_intel do
      sha256 "17869ea4873772b66c7d5e0ec1918a08471b8ebc6615dc78ffb0bce9928b1679"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f104f6f7dca9b52e3157f7ccf06e083cb961ea1b2c88bd05aa609fdc4b2ffd5"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8a04201a8a0e4d7d359792b56bff4771becb6e6db15c80ac1bf7f06b42645db1"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc0aa1d3a9e65ab17beac188681b1807f2e705b65c9a3892e298060f7fecc290"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_linux_arm64.tar.gz"
    end
  end

  name "durablex"
  desc "Durable workflow engine - a single Go binary with an embedded dashboard"
  homepage "https://github.com/easydep/durablex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "durablex"

  # No zap stanza required

end
